//
// デファイン定義
//

export const Define = {
    // ベースSVGイメージサイズ
    svgimagesize: {
        width:  842,
        height: 1192,
    },

    // グリッドサイズ
    grid: {
        width: 10,
        height: 10,
    },

    // ハンドルサイズ
    handle: {
        width: 10,
        height: 10,
    },
};

export const PresenBox = {
    A: [
        {
            id: 'box1',
            type: 'text',
            group: 'グループA',
            no: 1,
            x1: 400,
            y1: 100,
            x2: 700,
            y2: 300,
    
            text: {
                kumihoko: 'tate',
                padding_js: 10,
                padding_je: 10,
                padding_gs: 10,
                padding_ge: 10,
                size_j: 20,
                size_g: 20,
                gyokan: 5,
            },
            textgrid: [],
            textResult: [],
        },
        {
            id: 'box2',
            type: 'text',
            group: 'グループA',
            no: 2,
            x1: 400,
            y1: 350,
            x2: 700,
            y2: 550,
    
            text: {
                kumihoko: 'tate',
                padding_js: 10,
                padding_je: 10,
                padding_gs: 10,
                padding_ge: 10,
                size_j: 20,
                size_g: 20,
                gyokan: 5,
            },
            textgrid: [],
            textResult: [],
        },
        {
            id: 'box3',
            type: 'text',
            group: 'グループA',
            no: 3,
            x1: 400,
            y1: 600,
            x2: 700,
            y2: 800,
    
            text: {
                kumihoko: 'tate',
                padding_js: 10,
                padding_je: 10,
                padding_gs: 10,
                padding_ge: 10,
                size_j: 20,
                size_g: 20,
                gyokan: 5,
            },
            textgrid: [],
            textResult: [],
        },
    
        {
            id: 'box4',
            type: 'image',
            group: 'グループB',
            no: 1,
            x1: 100,
            y1: 100,
            x2: 350,
            y2: 300,

            image: '',
        },
    ],

    B: [
        { // アマゾンジャパン
            id: 'box001',
            type: 'text',
            group: 'K1M1',
            no: 1,
            x1: 70,
            y1: 70,
            x2: 150,
            y2: 100,
    
            text: {
                kumihoko: 'yoko',
                padding_js: 4,
                padding_je: 4,
                padding_gs: 10,
                padding_ge: 10,
                size_j: 9,
                size_g: 9,
                gyokan: 5,
            },
            textgrid: [],
            textResult: [],
        },
        { // 1000人の新規採用 
            id: 'box002',
            type: 'text',
            group: 'K1M1',
            no: 2,
            x1: 70,
            y1: 100,
            x2: 120,
            y2: 370,
    
            text: {
                kumihoko: 'tate',
                padding_js: 0,
                padding_je: 15,
                padding_gs: 10,
                padding_ge: 10,
                size_j: 25,
                size_g: 28,
                gyokan: 5,
            },
            textgrid: [],
            textResult: [],
        },
        { // 有料会員増加やサービス拡張で 
            id: 'box003',
            type: 'text',
            group: 'K1M1',
            no: 3,
            x1: 120,
            y1: 100,
            x2: 150,
            y2: 370,
    
            text: {
                kumihoko: 'tate',
                padding_js: 20,
                padding_je: 5,
                padding_gs: 0,
                padding_ge: 10,
                size_j: 17,
                size_g: 17,
                gyokan: 5,
            },
            textgrid: [],
            textResult: [],
        },
        { // 記事01 の本文01 
            id: 'box004',
            type: 'text',
            group: 'K1H1',
            no: 1,
            x1: 150,
            y1: 70,
            x2: 250,
            y2: 170,
    
            text: {
                kumihoko: 'tate',
                padding_js: 5,
                padding_je: 5,
                padding_gs: 5,
                padding_ge: 5,
                size_j: 9,
                size_g: 10,
                gyokan: 5,
            },
            textgrid: [],
            textResult: [],
        },
        { // 記事01 の本文02 
            id: 'box005',
            type: 'text',
            group: 'K1H1',
            no: 2,
            x1: 150,
            y1: 170,
            x2: 250,
            y2: 270,
    
            text: {
                kumihoko: 'tate',
                padding_js: 5,
                padding_je: 5,
                padding_gs: 5,
                padding_ge: 5,
                size_j: 9,
                size_g: 10,
                gyokan: 5,
            },
            textgrid: [],
            textResult: [],
        },
        { // 記事01 の本文03 
            id: 'box006',
            type: 'text',
            group: 'K1H1',
            no: 3,
            x1: 150,
            y1: 270,
            x2: 340,
            y2: 370,
    
            text: {
                kumihoko: 'tate',
                padding_js: 5,
                padding_je: 5,
                padding_gs: 5,
                padding_ge: 5,
                size_j: 9,
                size_g: 10,
                gyokan: 5,
            },
            textgrid: [],
            textResult: [],
        },
        { // 記事01 の本文04 
            id: 'box007',
            type: 'text',
            group: 'K1H1',
            no: 4,
            x1: 70,
            y1: 370,
            x2: 340,
            y2: 470,
    
            text: {
                kumihoko: 'tate',
                padding_js: 5,
                padding_je: 5,
                padding_gs: 10,
                padding_ge: 5,
                size_j: 9,
                size_g: 10,
                gyokan: 5,
            },
            textgrid: [],
            textResult: [],
        },
        { // 記事01 の本文05 
            id: 'box008',
            type: 'text',
            group: 'K1H1',
            no: 5,
            x1: 70,
            y1: 470,
            x2: 130,
            y2: 570,
    
            text: {
                kumihoko: 'tate',
                padding_js: 5,
                padding_je: 5,
                padding_gs: 10,
                padding_ge: 0,
                size_j: 9,
                size_g: 10,
                gyokan: 5,
            },
            textgrid: [],
            textResult: [],
        },
        { // 記事01 の本文06 
            id: 'box009',
            type: 'text',
            group: 'K1H1',
            no: 6,
            x1: 70,
            y1: 570,
            x2: 130,
            y2: 670,
    
            text: {
                kumihoko: 'tate',
                padding_js: 5,
                padding_je: 5,
                padding_gs: 10,
                padding_ge: 0,
                size_j: 9,
                size_g: 10,
                gyokan: 5,
            },
            textgrid: [],
            textResult: [],
        },
        { // 記事01 の画像 
            id: 'box010',
            type: 'image',
            group: 'K1I1',
            no: 1,
            x1: 260,
            y1: 70,
            x2: 400,
            y2: 260,
    
            image: '',
        },
        { // 記事01 の本文06 
            id: 'box011',
            type: 'text',
            group: 'K1C1',
            no: 1,
            x1: 400,
            y1: 70,
            x2: 440,
            y2: 270,
    
            text: {
                kumihoko: 'tate',
                padding_js: 15,
                padding_je: 15,
                padding_gs: 7,
                padding_ge: 0,
                size_j: 10,
                size_g: 10,
                gyokan: 5,
            },
            textgrid: [],
            textResult: [],
        },
        { // 記事02 の見出し01 オイシックス・ラ・大地  経営統合へに新社名変更
            id: 'box012',
            type: 'text',
            group: 'K2M1',
            no: 1,
            x1: 140,
            y1: 470,
            x2: 190,
            y2: 570,
    
            text: {
                kumihoko: 'tate',
                padding_js: 5,
                padding_je: 5,
                padding_gs: 10,
                padding_ge: 0,
                size_j: 8,
                size_g: 12,
                gyokan: 8,
            },
            textgrid: [],
            textResult: [],
        },
        { // 記事02 の見出し01 オイシックスドット大地
            id: 'box013',
            type: 'text',
            group: 'K2M1',
            no: 2,
            x1: 190,
            y1: 470,
            x2: 200,
            y2: 570,
    
            text: {
                kumihoko: 'tate',
                padding_js: 17,
                padding_je: 5,
                padding_gs: 0,
                padding_ge: 0,
                size_j: 7,
                size_g: 7,
                gyokan: 10,
            },
            textgrid: [],
            textResult: [],
        },
        { // 記事02 の本文01
            id: 'box014',
            type: 'text',
            group: 'K2H1',
            no: 1,
            x1: 200,
            y1: 470,
            x2: 340,
            y2: 570,
    
            text: {
                kumihoko: 'tate',
                padding_js: 5,
                padding_je: 5,
                padding_gs: 15,
                padding_ge: 5,
                size_j: 9,
                size_g: 10,
                gyokan: 5,
            },
            textgrid: [],
            textResult: [],
        },
        { // 記事02 の本文01
            id: 'box015',
            type: 'text',
            group: 'K2H1',
            no: 2,
            x1: 140,
            y1: 570,
            x2: 250,
            y2: 670,
    
            text: {
                kumihoko: 'tate',
                padding_js: 5,
                padding_je: 5,
                padding_gs: 15,
                padding_ge: 5,
                size_j: 9,
                size_g: 10,
                gyokan: 5,
            },
            textgrid: [],
            textResult: [],
        },
        { // 記事03 の見出し01
            id: 'box016',
            type: 'text',
            group: 'K3M1',
            no: 1,
            x1: 460,
            y1: 70,
            x2: 640,
            y2: 100,
    
            text: {
                kumihoko: 'yoko',
                padding_js: 55,
                padding_je: 55,
                padding_gs: 8,
                padding_ge: 8,
                size_j: 14,
                size_g: 14,
                gyokan: 5,
            },
            textgrid: [],
            textResult: [],
        },
    ],
};

export const PresenSozai = {
    A: [
        {
            id: '素材 ﾃｷｽﾄ',
            type: 'text',
            text: '　生産年齢人口の減少や第４次産業革命への対応など、建設業は大きな転換期を迎えている。３月に設立７０周年を迎えた全国建設業協会の近藤晴貞会長は、地域建設業が役割を果たし続けるために、「働き方改革と生産性向上に果敢に挑戦しなければならない」とし、「自ら改革を進めていくことも重要になる」と強調する。７０周年を契機に策定した「地域建設業将来展望」には、転換期を変革の好機に変えるためのキーワードを盛り込んだ。地域建設業の進化を後押しするため、全建は今後も各建設業協会の活躍を強力に推進するエンジンであり続ける。\n　近藤会長は、地域建設業に求められる役割について、「安全・安心の確保だけではなく、住民の利便性向上や地域経済の活性化など多岐にわたる」とした上で、「安全・安心の確保という切り口だけでなく、将来の地域建設業のあるべき姿を議論していかなければならない」と指摘する。\n　将来展望では、強みである「地域建設企業力」を生かした新時代の構築を打ち出し、インフラ老朽化対策での川上段階からの参画など、積極的な事業提案への取り組みを１つの方向性として示している。\n　視線の先にあるのは、地域建設業の持続的な発展であり、近藤会長は「若者が先を見通すことができる環境づくりの基盤を、年配の方々がつくる」という考えがベースになっていると説明する。\n　とはいえ、さまざまな施策が立案されても、経営の健全化がなければ実現は難しい。働き方改革や生産性向上の原資となる「健全な経営の継続」のためには、「仕事があり、仕事をこなす人がいて、利潤が出るという仕組みづくりをしなければならない」と強調する。\n　公共事業予算は下げ止まりの傾向が見られているが、今後も必要な仕事量を確保できるかどうかが地域ごとに異なる状況下で、「システムなどのサポートがなければできない部分もあるが、自ら仕事量を確保していくという取り組みも考えていく必要がある」と、積極果敢なチャレンジを生き残りの重要な要素に挙げる。\n　地域建設業が新時代を切り開くためには、公共事業予算の持続的・安定的な確保が重要な役割を果たすが、「予算の配分が一番大きな課題になる」とし、地域建設業、中小企業向けの予算確保に向けた活動を引き続き展開する。\n　働き方改革では、会員が現行の休日実績を１日増やす「休日月１＋（ツキイチプラス）」運動を展開するほか、「単価引き上げ分アップ宣言」に基づき、公共工事設計労務単価の改定分を下請に反映するための取り組みも徹底する。\n　建設キャリアアップシステムに対しては、「技能者の保有資格や就労実績を蓄積することで処遇の改善、技能の研さんにつながる。働き方改革、中長期的な担い手確保の面で、良い仕組みだと思う」と期待を寄せる。\n　新たな一歩を踏み出した全建の今後の役割として近藤会長は、各建協と会員企業が活動しやすい環境づくりや、地域建設業の魅力発信などを挙げる。「各建協単独では取り組みが難しいテーマや課題も、全建で集約すれば全国の声として発信することができる」とし、引き続き「地域建設業の地位向上と発展に寄与し続けていきたい」と力を込める。',
            mojiObjAry: [],
            image: '',
    
            select: '',
        },
        {
            id: '素材 画像',
            type: 'image',
            text: '',
            mojiObjAry: [],
            image: 'image/layoutA.jpg',
        },
    ],

    B: [
        {
            id: 'K1M1',
            type: 'text',
            text: 'アマゾンジャパン\n１０００人の新規採用\n有料会員増加やサービス拡張で',
            mojiObjAry: [],
            image: '',
    
            select: '',
        },
        {
            id: 'K1H1',
            type: 'text',
            text: '　アマゾンジャパンは５月２日、コーポレート職や技術職などの職種について、全国で１０００人規模の新規採用を行うと発表した。Ａｍａｚｏｎの有料会員であるプライム会員の増加や、自動音声サービス「Ａｌｅｘａ（アレクサ）」などのサービスの拡張などを背景に、対応する人員の確保に乗り出す。採用の強化に伴い、東京・目黒の駅前ビル内に、オフィスを新設する。\n　新規採用は、１９年にかけて行う。中途採用のほか、大学卒や専門学校卒を対象とした新卒採用も行う。採用するのは、クラウドコンピューティングなどに通じた技術職や、マーケティング・財務を担う職種が対象だ。\n　東京・目黒に新設するオフィスでは、その日の業務内容に合わせて働く場所を選択できるようにする。機密性の高い商談なども行えるよう、プライベートブースも設ける。オールジェンダー向けのトイレやシャワールーム、礼拝室も備える予定。多様な人材を対象に採用を進めるとみられる。\n　アマゾンジャパンのジャスパー・チャン社長は、「日本はＡｍａｚｏｎにとって世界でも戦略的に重要な国の一つ。生産性の向上や働き方改革、ダイバーシティーの推進に取り組んでいく」としている。',
            mojiObjAry: [],
            image: '',
    
            select: '',
        },
        {
            id: 'K1I1',
            type: 'image',
            text: '',
            mojiObjAry: [],
            image: 'image/K1I1.jpg',
    
            select: '',
        },
        {
            id: 'K1C1',
            type: 'text',
            text: '新オフィスが入居する目黒セントラルスクエア',
            mojiObjAry: [],
            image: '',
    
            select: '',
        },
        {
            id: 'K2M1',
            type: 'text',
            text: 'オイシックス・ラ・大地\n経営統合へに新社名変更\nオイシックスドット大地',
            mojiObjAry: [],
            image: '',
    
            select: '',
        },
        {
            id: 'K2H1',
            type: 'text',
            text: '　オイシックスドット大地は、１０月に予定しているらでぃっしゅぼーや（本社東京都、高島宏平社長）との経営統合へ向け、新社名を「オイシックス・ラ・大地株式会社」にすることを決めた。\n　経営統合に先駆けて７月１日付で社名を変更。１０月９日にらでぃっしゅぼーや社員はオイシックス・ラ・大地の本社（品川区大崎）に転籍する。',
            mojiObjAry: [],
            image: '',
    
            select: '',
        },
        {
            id: 'K3M1',
            type: 'text',
            text: '楽　　　天\n「楽天アイリス」を開発\nビッグデータを分析活用',
            mojiObjAry: [],
            image: '',
    
            select: '',
        },
    ],
};

export const PresenLine = {
    A: [

    ],

    B: [
        {
            id: 'line001',
            type: 'rect',
            x1: 65,
            y1: 65,
            x2: 775,
            y2: 1142,
    
            width: 0.5,
            color: '#000000',
        },
    ],
};
